turtle.setPosition(0, 4)
turtle.pen(TurtlePenMode.Down)
turtle.forward(5)
turtle.setPosition(1, 2)
turtle.forward(1)
turtle.setPosition(2, 2)
turtle.forward(1)
turtle.setPosition(3, 2)
turtle.forward(1)
turtle.setPosition(2, 2)
turtle.forward(1)
turtle.forward(5)
